### ISSUE TITLE
Could not resolve placeholder 'sys-name' in value "${sys-name}"

### ISSUE THREAD

**Issue by LazarIliev** [BSN-Spartan/Data-Center-System#5]
I am trying to deploy and start Datacenter locally on my machine.

I got this stack trace:
```
2023-01-25 17:35:38.465   ERROR[main]org.springframework.boot.SpringApplication.reportFailure:819 -Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ncSdkConfigInfo': Unsatisfied dependency expressed through field 'sendMessageService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sendMessageServiceImpl': Unsatisfied dependency expressed through field 'emailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sys-name' in value "${sys-name}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
	at com.spartan.dc.SpartanDcApplication.main(SpartanDcApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sendMessageServiceImpl': Unsatisfied dependency expressed through field 'emailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sys-name' in value "${sys-name}"
``` 

My first question is how to solve that? There is some `sys-name` variable not set or?

My second question is for the IPs. When I am locally starting db, node and this datacenter what do I need to do in order for the configuration in the `application.yml` and `application-prod.yml` to work? Can you elaborate on that a bit more? Because in the video you just set the IP but does that mean that I need to use my public Ip and forward the db's port/3306 to be accessible to the public?

The `Configure the email` part for gmail how needs to be done. Is this correct? And do we need something more, SSL etc.? 
```
host: smtp.gmail.com
    port: 587
```

**Comment by billjackson5** [comment]
> I am trying to deploy and start Datacenter locally on my machine.
> 
> I got this stack trace:
> 
> ```
> 2023-01-25 17:35:38.465   ERROR[main]org.springframework.boot.SpringApplication.reportFailure:819 -Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ncSdkConfigInfo': Unsatisfied dependency expressed through field 'sendMessageService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sendMessageServiceImpl': Unsatisfied dependency expressed through field 'emailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sys-name' in value "${sys-name}"
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
> 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
> 	at com.spartan.dc.SpartanDcApplication.main(SpartanDcApplication.java:16)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
> 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sendMessageServiceImpl': Unsatisfied dependency expressed through field 'emailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sys-name' in value "${sys-name}"
> ```
> 
> My first question is how to solve that? There is some `sys-name` variable not set or?
> 
> My second question is for the IPs. When I am locally starting db, node and this datacenter what do I need to do in order for the configuration in the `application.yml` and `application-prod.yml` to work? Can you elaborate on that a bit more? Because in the video you just set the IP but does that mean that I need to use my public Ip and forward the db's port/3306 to be accessible to the public?
> 
> The `Configure the email` part for gmail how needs to be done. Is this correct? And do we need something more, SSL etc.?
> 
> ```
> host: smtp.gmail.com
>     port: 587
> ```

Hi Lazar,
1. I think you are trying to update the data center and run the latest version of mysql database. "sys-name" parameter is used in the previous version of data center, and has been removed. Please update application.yaml and application-prod.yaml files before starting the data center system.
2. The video is just an example. For your safety and privacy, please use the LAN IP address. We also recommend you use domain name to access the system.
3. Apart from the host and the port, the username and password parameters are also in need. The password here is the 2-step verification password of the email.
